config/routes.rb
Rails.application.routes.draw do
  root "homes#show"

  scope "(:locale)", locale: /en|es/ do
    resources :lists, param: :share_id, only: %i[index new create update]
    get "lists/:share_id", to: "lists#edit"
  end

  resources :lists, param: :share_id, only: %i[index new create update]
  get "lists/:share_id", to: "lists#edit"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :list
end

app/models/list.rb
class List < ApplicationRecord
  has_many :items, dependent: :destroy

  before_create :generate_share_id

  accepts_nested_attributes_for :items, allow_destroy: true, reject_if: :all_blank

  def to_param
    share_id
  end

  private

  def generate_share_id
    loop do
      self.share_id = SecureRandom.alphanumeric(10)
      break unless List.exists?(share_id:)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_locale

  private

  def set_locale
    I18n.locale = params[:locale] || browser_locale || I18n.default_locale
  end

  def browser_locale
    request.env["HTTP_ACCEPT_LANGUAGE"].to_s.scan(/^[a-z]{2}/).first
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  layout false

  def show
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: %i[show edit update destroy]
  before_action :refresh_list_ids_in_cookies

  def index
    @lists = List.where(share_id: list_ids_from_cookies)
  end

  def new
    @list = List.new
    @list.items.build
  end

  def edit
  end

  def create
    @list = List.new(list_params)

    if @list.save
      add_list_to_user_cookies
      redirect_to list_path(@list, locale: I18n.locale)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @list.update(list_params)
      redirect_to list_path(@list, locale: I18n.locale)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private

  def set_list
    @list = List.find_by!(share_id: params[:share_id])
  end

  def list_params
    params.require(:list).permit(:title, items_attributes: [:id, :description, :completed, :_destroy])
  end

  def list_ids_from_cookies
    return [] unless cookies[:lists]

    JSON.parse(cookies[:lists])
  end

  def add_list_to_user_cookies
    list_share_ids = cookies[:lists] ? JSON.parse(cookies[:lists]) : []
    list_share_ids << @list.share_id

    cookies[:lists] = JSON.generate list_share_ids
  end

  def refresh_list_ids_in_cookies
    return unless cookies[:lists]

    list_share_ids = JSON.parse(cookies[:lists])
    list_share_ids = List.where(share_id: list_share_ids).pluck :share_id

    cookies[:lists] = JSON.generate list_share_ids
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/homes/show.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ListMate</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
  </head>

  <body>
    <div class="flex flex-col min-h-screen">
      <div class="flex-grow">
        <header class="bg-white shadow">
          <div class="container mx-auto px-6 py-3">
            <div class="flex items-center justify-between">
              <div>
                <%= link_to "ListMate", root_path, class: "text-xl font-semibold text-gray-800" %>
              </div>
              <div class="hidden md:flex items-center">
                <nav class="font-semibold text-gray-800">
                  <a href="#" class="mx-4"><%= t('.menu.features') %></a>
                  <a href="#" class="mx-4"><%= t('.menu.pricing') %></a>
                  <a href="#" class="mx-4"><%= t('.menu.about') %></a>
                </nav>
                <%= link_to t('.menu.get_started'), new_list_path, class: "bg-blue-500 text-white px-6 py-2 rounded-md" %>
              </div>
            </div>
          </div>
        </header>

        <main class="container mx-auto px-6 py-12">
          <section class="text-center">
            <h1 class="text-4xl font-bold mb-4"><%= t('.main.heading') %></h1>
            <p class="text-xl text-gray-700"><%= t('.main.subheading') %></p>
            <div class="flex md:hidden justify-center mt-4">
              <%= link_to t('.menu.get_started'), new_list_path, class: "bg-blue-500 text-white px-6 py-2 rounded-md" %>
            </div>
          </section>

          <section class="mt-12 grid md:grid-cols-2 gap-8">
            <div>
              <h2 class="text-2xl font-bold mb-4"><%= t('.main.features.collaborative_lists.title') %></h2>
              <p class="text-gray-700"><%= t('.main.features.collaborative_lists.description') %></p>
            </div>
            <div>
              <h2 class="text-2xl font-bold mb-4"><%= t('.main.features.no_downloads.title') %></h2>
              <p class="text-gray-700"><%= t('.main.features.no_downloads.description') %></p>
            </div>
          </section>

          <section class="mt-12">
            <h2 class="text-2xl font-bold mb-4 text-center"><%= t('.main.pricing.title') %></h2>
            <div class="bg-white p-6 rounded-md shadow">
              <h3 class="text-xl font-bold mb-4"><%= t('.main.pricing.free_plan.title') %></h3>
              <ul class="list-disc pl-8 text-gray-700">
                <li><%= t('.main.pricing.free_plan.feature_1') %></li>
                <li><%= t('.main.pricing.free_plan.feature_2') %></li>
                <li><%= t('.main.pricing.free_plan.feature_3') %></li>
              </ul>
            </div>
          </section>
        </main>
      </div>

      <footer class="bg-white shadow mt-12">
        <div class="container mx-auto px-6 py-3">
          <div class="text-center text-gray-800">
            &copy; <%= Time.current.year %> ListMate. <%= t('.footer.rights_reserved') %>
          </div>
        </div>
      </footer>
    </div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ListMate</title>

    <%# META TAGS %>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%# END META TAGS %>

    <%# STYLESHEETS %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="https://ga.jspm.io/npm:tippy.js@6.3.7/dist/tippy.css" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="https://ga.jspm.io/npm:tippy.js@6.3.7/animations/scale-extreme.css" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%# END STYLESHEETS %>

    <%# JAVASCRIPT %>
    <script>window.process = { env: {} }</script>
    <%= javascript_importmap_tags %>
    <%# END JAVASCRIPT %>
  </head>

  <body>
    <div class="flex flex-col min-h-screen">
      <div class="flex-grow">

        <header class="bg-white shadow-sm" data-controller="mobile-menu">
          <div class="container mx-auto px-4 py-2 flex justify-between items-center">
            <div class="text-2xl font-bold text-gray-800">
              <%= link_to "ListMate", root_path %>
            </div>
            <nav class="hidden md:flex space-x-4 items-center">
              <%= link_to t('.menu.my_lists'), lists_path, class: "mx-4" %>
              <%= link_to t('.menu.create'), new_list_path, class: "bg-blue-500 text-white px-6 py-2 rounded-md" %>
            </nav>
            <button id="hamburger" class="md:hidden focus:outline-none"  data-action="click->mobile-menu#toggleMenu">
              <i class="fas fa-bars text-gray-800"></i>
            </button>
          </div>
          <div id="mobile-menu" class="hidden md:hidden absolute bg-white w-full left-0 mt-2 shadow-md z-10" data-mobile-menu-target="menu">
            <ul class="list-none p-0">
              <li>
                <%= link_to t(".menu.my_lists"), lists_path, class: "block px-4 py-2 text-gray-800 hover:bg-gray-200" %>
              </li>
              <li>
                <%= link_to t(".menu.create_list"), new_list_path, class: "block px-4 py-2 text-gray-800 hover:bg-gray-200" %>
              </li>
            </ul>
          </div>
        </header>

        <main class="container mx-auto mt-10 md:mt-20 px-5 flex">
          <%= yield %>
        </main>
      </div>

      <footer class="bg-white shadow mt-12">
        <div class="container mx-auto px-6 py-3">
          <div class="text-center text-gray-800">
            &copy; <%= Time.current.year %> ListMate. <%= t('.footer.rights_reserved') %>
          </div>
        </div>
      </footer>
    </div>
  </body>
</html>

app/views/lists/_form.html.erb
<%= form_with(model: list, local: true, class: "contents", data: { controller: "nested-form form" }, id: form_id) do |form| %>
  <% if list.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(list.errors.count, "error", locale: I18n.locale) %> prohibited this list from being saved:</h2>

      <ul>
        <% list.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <% if action_name == "new" %>
    <div>
      <%= form.label :title %>
      <%= form.text_field :title, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full", required: true %>
    </div>
  <% end %>

  <template data-nested-form-target='template'>
    <%= form.fields_for :items, Item.new, child_index: "TEMPLATE_RECORD" do |item_fields| %>
      <div class="nested-fields flex items-center border-b-2 py-2">
        <%= item_fields.hidden_field :_destroy %>
        <%= item_fields.check_box :completed, class: "w-6 h-6 text-blue-600 bg-gray-100 border-gray-300 rounded focus:ring-transparent" %>
        <% if action_name == "new" %>
          <%= item_fields.text_field :description, class: "mx-4 border-0 w-full focus:ring-transparent", required: true, placeholder: "Item" %>
        <% else %>
          <%= item_fields.text_field :description, class: "mx-4 border-0 w-full focus:ring-transparent", required: true, placeholder: "Item", data: { action: "form#submitWithDebounce" } %>
        <% end %>

        <%= link_to "#", data: { action: "nested-form#removeAssociation" } do %>
          <i class="fa-solid fa-trash-can text-red-500 text-xl"></i>
        <% end %>
      </div>
    <% end %>
  </template>

  <div class="mt-4">
    <% if action_name == "new" %>
      <h2>Items</h2>
    <% end %>
    <%= form.fields_for :items do |item_fields| %>
      <div class="nested-fields flex items-center border-b-2 py-2">
        <%= item_fields.hidden_field :_destroy %>
        <%= item_fields.check_box :completed, class: "w-6 h-6 text-blue-600 bg-gray-100 border-gray-300 rounded focus:ring-transparent" %>
        <% if action_name == "new" %>
          <%= item_fields.text_field :description, class: "mx-4 border-0 w-full focus:ring-transparent", required: true, placeholder: "Item" %>
        <% else %>
          <%= item_fields.text_field :description, class: "mx-4 border-0 w-full focus:ring-transparent", required: true, placeholder: "Item", data: { action: "form#submitWithDebounce" } %>
        <% end %>

        <%# <%= item_fields.text_field :description, class: "mx-4 shadow rounded-sm border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %1> %>

        <i class="fa-solid fa-trash-can text-red-500 text-xl" data-action="click->nested-form#removeAssociation click->form#submit"></i>
      </div>
    <% end %>
    <div data-nested-form-target="addItem">
    </div>
  </div>

  <div class="mt-8 flex justify-end">
    <%= link_to "+", "#", class: "rounded-lg py-3 px-5 bg-blue-600 text-white font-medium cursor-pointer", id: "add_item", data: { action: "nested-form#addAssociation" } %>
  </div>
<% end %>

app/views/lists/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <div class="flex justify-between mb-6">
    <h1 class="font-bold text-4xl">
      <%= t(".title", list: @list.title) %>
    </h1>
    <%= button_tag t(".share"), class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer", data: { controller: "clipboard", clipboard_tooltip_content_value: t(".copy_tooltip_msg") } %>
  </div>

  <%= render "form", list: @list, form_id: "edit-list-form" %>
</div>

app/views/lists/index.html.erb
<div class="w-full">
  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl"><%= t(".lists") %></h1>
    <%= link_to t(".new_list"), new_list_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="lists" class="min-w-full">
    <% @lists.each do |list| %>
      <%= tag.div id: dom_id(list) do %>
        <p class="my-5">
          <strong class="block font-medium mb-1"><%= "#{List.human_attribute_name(:title)}:" %></strong>
          <%= list.title %>
        </p>

        <%= link_to t(".show"), list_path(list, locale: I18n.locale), class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/lists/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <div class="flex justify-between mb-6">
    <h1 class="font-bold text-4xl"><%= t(".new_list") %></h1>
    <button type="submit" form="new-list-form" class="rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer"><%= t(".create") %></button>
  </div>

  <%= render "form", list: @list, form_id: "new-list-form" %>
</div>